### ISSUE TITLE
Cannot build an app on Flutter 1.9.1

### ISSUE THREAD

**Issue by ragnor-rs** [AppsFlyerSDK/appsflyer-flutter-plugin#10]
**Describe the bug**
It seems that appsflyer_sdk-1.1.3 is not compatible with Flutter v1.9.1+hotfix.2

**To Reproduce**
1. Create a Flutter project
2. Depend on appsflyer_sdk: 1.1.3
3. Run `flutter build ios --simulator`
4. See error:
```
/Library/flutter/.pub-cache/hosted/pub.dartlang.org/appsflyer_sdk-1.1.3/ios/Classes/AppsflyerSdkPlugin.m:272
    :32: error: no visible @interface for 'FlutterViewController' declares the selector 'sendOnChannel:message:binaryReply:'
            [flutterViewController sendOnChannel:channel message:dataFromDict binaryReply:^(NSData * _Nullable reply) {
             ~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
```

**Expected behavior**
The app is built successfully

**Screenshots**
N/A

**Desktop (please complete the following information):**
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-RU)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Community Edition (version 2018.1)
[✓] VS Code (version 1.31.1)
[✓] Connected device (1 available)
```

**Smartphone (please complete the following information):**
N/A (building for simulator)

**Additional context**
The plugin works with the previous stable version of Flutter (1.7.8+hotfix.4)

**Comment by tamanugi** [comment]
I happened same issue. Any progress on this issue?

@ShaharAF @af-fess
