### ISSUE TITLE
validateAndLogInAppPurchase on iOS will crash sometimes on validation error.

### ISSUE THREAD

**Issue by Moncader** [AppsFlyerSDK/appsflyer-flutter-plugin#111]
Executing validateAndLogInAppPurchase with information that will cause an error will cause the app to crash.

**To Reproduce**
1. Purchase something (in my case auto-renewable subscription and in Sandbox mode)
2. Pass the information to validateAndLogInAppPurchase, but do not set Sandbox mode for AppFlyer.
3. Crash

**Expected behavior**
No crash.

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - OS: iOS 14.2
 - Browser: Safari

**Additional context**
The crash is
```
NSInvalidArgumentException
*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
```

It happens because -(void)onValidateFail:(NSError*)error{ is executed with error being nil, which according to the AppsFlyer iOS SDK is valid.
In the next line, you're attempting to make a dictionary using that error.description which is nil.

**Comment by GM-appsflyer** [comment]
Hey @Moncader ,
Thanks for reaching out!

Just pushed a fix in version **6.2.4+4-nullsafety**
