### ISSUE TITLE
After clicking FB ADS can not get the data in onAppOpenAttribution

### ISSUE THREAD

**Issue by oyzxchi** [AppsFlyerSDK/appsflyer-flutter-plugin#121]
When I put oneLink use in Facebook ads above, click on the ad to jump to my application, Deferred Deep Linking is normal. But when I have installed the app, I can only get the following data when I click on the ad:
![image](https://user-images.githubusercontent.com/78333154/115554787-6de50900-a2e1-11eb-81ea-b54980ba2879.png)
![image](https://user-images.githubusercontent.com/78333154/115555468-1e530d00-a2e2-11eb-94fa-adfdeaef6387.png)

or:
![image](https://user-images.githubusercontent.com/78333154/115556230-0760ea80-a2e3-11eb-8326-15d5edb19d2f.png)
![image](https://user-images.githubusercontent.com/78333154/115556173-f7490b00-a2e2-11eb-8be2-f861c254c68b.png)

I want to know how to get information oneLink when I click on the corresponding FB ADS

**Comment by GM-appsflyer** [comment]
Hey @oyzxchi ,

Did you made sure to use the facebook api?
https://github.com/AppsFlyerSDK/appsflyer-flutter-plugin/blob/master/doc/API.md#enableFacebookDeferredApplinks
Check the following article also:
https://support.appsflyer.com/hc/en-us/articles/207033826-Facebook-Ads-setup-guide#advanced-using-facebook-ads-appsflyer-sdks-for-deferred-deep-linking

**Comment by GM-appsflyer** [comment]
Hey @oyzxchi ,

Are you getting the facebook relevant data (campaign etc) when deferred deep linking?

**Comment by GM-appsflyer** [comment]
Closing this issue but please reach out if you still need any help!
