### ISSUE TITLE
 AppsFlyer App Tracking Transparency (ATT) support

### ISSUE THREAD

**Issue by diegoveloper** [AppsFlyerSDK/appsflyer-flutter-plugin#123]
We received a mail/notification apple about the ATT integration in our app, since we are using `appsflyer-flutter-plugin` , is this plugin handling the permission request when it's initialized?
Otherwise, do we have to add iOS code manually? 

I checked this page about the config https://support.appsflyer.com/hc/en-us/articles/207032066#integration-33-configuring-app-tracking-transparency-att-support but it's all native code.
Do you have something similar for Flutter?

**Comment by GM-appsflyer** [comment]
Hey @diegoveloper ,
Please find full implementation required here:
https://github.com/AppsFlyerSDK/appsflyer-flutter-plugin#ios14
Because `requestTrackingAuthorizationWithCompletionHandler` is taken from Apple class, it's required to implement it on the native side as well.
