### ISSUE TITLE
how to record app uninstall event to af dashboard ??

### ISSUE THREAD

**Issue by wangxingxing123654** [AppsFlyerSDK/appsflyer-flutter-plugin#127]
[https://support.appsflyer.com/hc/en-us/articles/210289286-Uninstall-measurement](https://support.appsflyer.com/hc/en-us/articles/210289286-Uninstall-measurement)
this article is about native code, but how  did af-flutter-sdk to implete this

**Comment by wangxingxing123654** [comment]
> https://support.appsflyer.com/hc/en-us/articles/210289286-Uninstall-measurement
> this article is about native code, but how did af-flutter-sdk to implete this

android has followed the [doc,but](https://support.appsflyer.com/hc/en-us/articles/360017822118--WIP-Integrate-Android-uninstall-measurement-into-an-app),but no uninstalls in Aggregated performance report

**Comment by pazlavi** [comment]
Hi @wangxingxing123654, 
Thank you for reaching out to us. 

You have to configure the uninstall measurement in your dashboard ([Android](https://support.appsflyer.com/hc/en-us/articles/360017822118--WIP-Integrate-Android-uninstall-measurement-into-an-app#connect-fcm-api-to-appsflyer), [IOS](https://support.appsflyer.com/hc/en-us/articles/360017822178#get-id-in-apple-and-set-uninstall-measurement-in-appsflyer)).
After the integration in your dashboard is set, you can follow the native implementation ([Android](https://support.appsflyer.com/hc/en-us/articles/360017822118--WIP-Integrate-Android-uninstall-measurement-into-an-app#integrate-fcm-into-the-app), [IOS](https://support.appsflyer.com/hc/en-us/articles/360017822178#integrate-with-the-sdk)) or use a 3rd party plugin to receive the token (based on the OS) and send the toke to AppsFlyer servers using [this API](https://github.com/AppsFlyerSDK/appsflyer-flutter-plugin/blob/master/doc/API.md#updateServerUninstallToken)

**Comment by GM-appsflyer** [comment]
Closing this issue, but please let us know if you still need help or open a ticket at support@appsflyer.com

**Comment by AlexandrFarkas** [comment]
@GM-appsflyer Is that ok to pass token from FirebaseMessaging.instance.onTokenRefresh to sdk.updateServerUninstallToken() for both platforms (iOS and Android)?

**Comment by pazlavi** [comment]
Hi @AlexandrFarkas,

You should use `getAPNSToken` for IOS. 
```dart
  ///update Uninstall Token
  void _updateToken() {
    if (Platform.isAndroid) {
      FirebaseMessaging.instance.getToken().then((token) => token != null
          ? _appsflyerSdk?.updateServerUninstallToken(token)
          : null);
    } else if (Platform.isIOS) {
      FirebaseMessaging.instance.getAPNSToken().then((token) => token != null
          ? _appsflyerSdk?.updateServerUninstallToken(token)
          : null);
    }
  }
```

**Comment by SametSahin10** [comment]
> Hi @AlexandrFarkas,
> 
> You should use `getAPNSToken` for IOS.
> 
> ```dart
>   ///update Uninstall Token
>   void _updateToken() {
>     if (Platform.isAndroid) {
>       FirebaseMessaging.instance.getToken().then((token) => token != null
>           ? _appsflyerSdk?.updateServerUninstallToken(token)
>           : null);
>     } else if (Platform.isIOS) {
>       FirebaseMessaging.instance.getAPNSToken().then((token) => token != null
>           ? _appsflyerSdk?.updateServerUninstallToken(token)
>           : null);
>     }
>   }
> ```

There isn't something similar to this in the documentation that is about setting up uninstall measurement in a Flutter app. It would be great if we have a separate section that includes instructions to integrate the feature for Flutter.

**Comment by alamen-pgooja** [comment]
https://github.com/AppsFlyerSDK/appsflyer-flutter-plugin/issues/127#issuecomment-890493425
when exactly I should fire _updateToken method? in SDK initialization?

**Comment by monkeydaichan** [comment]
Help me check issue comments

**Comment by Dani-Koza-AF** [comment]
Will be added to official docs
