### ISSUE TITLE
could we support  with  flutter  6.2.4-flutterv1  which fixed the ios deeplinks

### ISSUE THREAD

**Issue by wangxingxing123654** [AppsFlyerSDK/appsflyer-flutter-plugin#132]
because  many flutter apps are not support flutter 2.0, so we could not use the newest appsflyer-flutter-plugin package, cuold you mind fixed the deeplinking which  versions are 6.2.4-flutterv1

**Comment by GM-appsflyer** [comment]
Hey @wangxingxing123654 ,

We recommend updating to Flutter 2.0. Unfortunately, we're not going to maintain the plugin with Flutter V1 anymore.
