### ISSUE TITLE
conversion data problem

### ISSUE THREAD

**Issue by chicksick** [AppsFlyerSDK/appsflyer-flutter-plugin#134]
onInstallConversion callbacks always return organic install, but in dashboard I see non-organic installs.

```{"status": "success", "payload": {"af_status": "Organic", "af_message": "organic install", "install_time": "2021-06-17 15:45:30.277", "is_first_launch": true}}```

**Comment by maxsalo17** [comment]
I have the same problem. @chicksick how you solved that problem?

**Comment by AhmadIzaz** [comment]
how did you solved this ?? @maxsalo17 @chicksick
