### ISSUE TITLE
Can't get advertisingIdentifier

### ISSUE THREAD

**Issue by a313** [AppsFlyerSDK/appsflyer-flutter-plugin#136]
I want to get advertisingIdentifier like native sdk but it look like it doesnt support yet

**Comment by GM-appsflyer** [comment]
Hey @a313 ,

We don't have an official API for fetching advertisingIdentifier, I'm guessing you're able to get it for one of the classes properties.

**Comment by a313** [comment]
Here is where i get advertisingIdentifier on native IOS

> Hey @a313 ,
> 
> We don't have an official API for fetching advertisingIdentifier, I'm guessing you're able to get it for one of the classes properties.

Thanks for your response.
Here is where I get the advertisingIdentifier on native IOS. But I cant find a solution on flutter.
![Screen Shot 2021-07-06 at 09 27 18](https://user-images.githubusercontent.com/6405454/124533538-b28e3400-de3c-11eb-9075-60e0a5796ad4.png)

**Comment by GM-appsflyer** [comment]
Hey @a313 ,

It's not possible to get this property from flutter side.
I would recommed using 3rd part library for fetching the IDFA for iOS.
Try the following: https://pub.dev/packages/app_tracking_transparency
```
  void _requestATTPermission() {
    if (Platform.isIOS) {
      AppTrackingTransparency.requestTrackingAuthorization()
          .then((status) async {
        print(status);
        if (status == TrackingStatus.authorized) {
          var idfa = await AppTrackingTransparency.getAdvertisingIdentifier();
          print("IDFA is $idfa");
        }
      });
    }
  }
```

**Comment by GM-appsflyer** [comment]
Closing this issue, but please let us know if there is anything else we can help you with!

**Comment by a313** [comment]
Thanks
