### ISSUE TITLE
For some reason 'conversions.appsflyer.com' is blocked on Android

### ISSUE THREAD

**Issue by AlexanderFarkas** [AppsFlyerSDK/appsflyer-flutter-plugin#140]
I've tried to test through "SDK Integration" in Appsflyer Console.

For some reason, request to server was blocked .
I needed to add 'conversions.appsflyer.com' to cleartext exceptions.

Probably you mistyped 'http' instead of 'https' somewhere in the code?

Version: ^6.2.4+4-nullsafety

**Comment by DevAKS-Yara** [comment]
@AlexanderFarkas How did you find that 'conversions.appsflyer.com'  was blocked?
