### ISSUE TITLE
^6.3.5+2 upgrade breaks code from  ^6.3.5+1 

### ISSUE THREAD

**Issue by ernesto** [AppsFlyerSDK/appsflyer-flutter-plugin#156]
**Describe the bug**
After upgrade to version ^6.3.5+2 from ^6.3.5+1, the event (dynamic) changes to DeepLinkResult without '[]' access.

```
_appsflyerSdk.onDeepLinking((event) {
      final payload = event["payload"];
}

Error: The operator '[]' isn't defined for the class 'DeepLinkResult'.
```

**Expected behavior**
After a minor update like that, the project needs work.

**Additional context**
That is critical into CI environments, for example.

**Comment by GM-appsflyer** [comment]
Hey @ernesto ,

Please update to v6.3.5+3, as the breaking changes were moved to next version (6.4.0).
