### ISSUE TITLE
`deepLinkValue`: type 'Null' is not a subtype of type 'String' in type cast

### ISSUE THREAD

**Issue by pierrea** [AppsFlyerSDK/appsflyer-flutter-plugin#164]
I'm getting this error since the latest update:

```
type 'Null' is not a subtype of type 'String' in type cast

flutter: When the exception was thrown, this was the stack:
flutter: #0      DeepLink.deepLinkValue (package:appsflyer_sdk/src/udl/deeplink.dart:16:64)
```
which corresponds to [this method](https://github.com/AppsFlyerSDK/appsflyer-flutter-plugin/blob/master/lib/src/udl/deeplink.dart#L16) of the `DeepLink` class:
```dart
String? get deepLinkValue =>  _clickEvent["deep_link_value"] as String;
```

I believe `as String` causes the problem because `_clickEvent["deep_link_value"]` can be null. I suggest making sure it's not null before casting, or removing the cast.

In the meantime I'm going to use `clickEvent['deep_link_value']` in my code as an alternative for `deepLinkValue` or any other get accessor here.

**Comment by GM-appsflyer** [comment]
Hey @pierrea 

A fix for this issue was released in 6.4.0+1.
