### ISSUE TITLE
possible re-enable IDFA via AppsflyerSdk.setDisableAdvertisingIdentifiers ? 

### ISSUE THREAD

**Issue by mpiparo** [AppsFlyerSDK/appsflyer-flutter-plugin#167]
Apologies if this is documented and I missed it, but is it possible to re-enable IDFA after init?
I notice there is a setDisableAdvertisingIdentifiers method, but it is not clear if I set this to false, after initializing with 'disableAdvertisingIdentifier: true' if this will re-enable IDFA?

Appreciate any clarification.

**Comment by af-fess** [comment]
Hey @mpiparo,
yes, `setDisableAdvertisingIdentifiers(false)` will tell to SDK to start to collect the IDFA

**Comment by GM-appsflyer** [comment]
Hey @mpiparo ,

This API exists only for Android.
I'll add it as a task to add for next versions for iOS also
