### ISSUE TITLE
I couldn't find AppsFlyerLib.getInstance().sendPushNotificationData(this) in the sdk.

### ISSUE THREAD

**Issue by alexandrepd** [AppsFlyerSDK/appsflyer-flutter-plugin#169]
I cant use sendPushNotificationData in Flutter sdk.

```
# Appsflyer SDK
  appsflyer_sdk: 6.2.3+1
```

I found this in ReactNative plugin:
https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/master/index.js#:~:text=appsFlyer.-,sendPushNotificationData,-%3D%20(pushPayload)%20%3D%3E%20%7B

Thanks for attetion!

**Comment by GM-appsflyer** [comment]
API added
