### ISSUE TITLE
Apps Flyer generating long link always 

### ISSUE THREAD

**Issue by satishsoni777** [AppsFlyerSDK/appsflyer-flutter-plugin#178]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fullflash** [comment]
same for us sometimes it sdk generates short link like it should be.
but in most times there is a long link generated which is completely useless 
appsflyer is far away to be a proper replacement for firebase dynamic link
