### ISSUE TITLE
Regex error in iOS app id

### ISSUE THREAD

**Issue by AdmiralMealty** [AppsFlyerSDK/appsflyer-flutter-plugin#180]
Appid in iOS expected to match regex "^\d{8,11}$", while it's value is "^id\d{8,11}$". For example, app id is "id12345678", not "12345678" how expected. In code in could be found in _validateMapOptions in these strings:
RegExp exp = RegExp(r'^\d{8,11}$');
assert(exp.hasMatch(appID));

**Comment by ge-af** [comment]
Hi @AdmiralMealty 

Thanks for reaching out to us!

The `appleAppId` you should input is only numbers, without the `id` prefix.
e.g. - "id111111999" should be "id1111119"

Please let me know if this solve the issue for you.

If not, we would kindly ask you to submit a support ticket to support@appsflyer.com.
When submitting the ticket, please specify your AppsFlyer sign-up (account) email, app ID, reproduction steps, code snippets, logs, the links you used, and any additional relevant information.

**Comment by AdmiralMealty** [comment]
Sorry, it was actually my fault. Thank you for your answer!
