### ISSUE TITLE
generateInviteLink terminated iOS application

### ISSUE THREAD

**Issue by razgovorov87** [AppsFlyerSDK/appsflyer-flutter-plugin#183]
I use AppsFlyers v6.4.4+1

After updating to a new version of the plugin, the generateInviteLink method terminated the application

```
final AppsFlyerInviteLinkParams inviteLinkParams = AppsFlyerInviteLinkParams(
      referrerName: '${user.name}',
      customerID: user.customId.toString(),
);

appsflyerSdk.generateInviteLink(inviteLinkParams, (result) {
         ...
});
```
![Снимок экрана 2021-12-14 в 18 53 33](https://user-images.githubusercontent.com/56688038/145994451-5102997e-567d-4260-8ba8-4c5642d57f58.png)

**Comment by GM-appsflyer** [comment]
Hey @razgovorov87 ,

We've released v6.4.4+2 with a fix to the issue.
