### ISSUE TITLE
Shortlink returns `null` for the `deepLinkValue`

### ISSUE THREAD

**Issue by RobertBrunhage** [AppsFlyerSDK/appsflyer-flutter-plugin#189]
**Describe the bug**
When generating a deep link it can either be with query params or make it a short link. Using query params the `deepLinkValue` is populated but using it as a short link all of the data coming back is `null`.

**To Reproduce**
1. Click "Redirect & Deep linking" tab
2. Add a Deep link value
3. Click update link
4. Click the link to open the app
5. All the values will be `null`

**Expected behavior**
The deep link value should be populated with the value set in AppsFlyer. Currently, it is only populated when making the link with query params.

**Screenshots**

Example working:
https://test.domain.com/ssdfs/sdfsdgsdg?model=Value1&id=Value2

Example not working:
https://test.domain.com/ssdfs/sdfsdgsdg

![image](https://user-images.githubusercontent.com/26344867/146233092-1d38a79c-4ac5-4acb-81b1-077bcae1f865.png)

**Smartphone (please complete the following information):**
 - OS: Android & iOS

**Comment by pazlavi** [comment]
Hi @RobertBrunhage ,
Thank you for reaching out to us.
To provide optimal support, we would kindly ask you to submit a support ticket to support@appsflyer.com.

When submitting the ticket, please specify your AppsFlyer sign-up (account) email, app ID, reproduction steps, code snippets, logs, the links you used, and any additional relevant information.

**Comment by Ableson** [comment]
onAppOpenAttribution no execution. Execute onInstallConversionData every time the app is opened. onDeepLinking show in image:
![image](https://user-images.githubusercontent.com/67767856/148167474-77e19079-d785-49c1-b5e7-905ed04c810b.png)

**Comment by ge-af** [comment]
Hi @Ableson 

We are not sure might be the exact issue you are referring to.

We would kindly ask you too to submit a support ticket to support@appsflyer.com in order to get optimal support.
When submitting the ticket, please specify your AppsFlyer sign-up (account) email, app ID, reproduction steps, code snippets, logs, the links you used, and any additional relevant information.

**Comment by Ableson** [comment]
> Hi @Ableson
> 
> We are not sure might be the exact issue you are referring to.
> 
> We would kindly ask you too to submit a support ticket to [support@appsflyer.com](mailto:support@appsflyer.com) in order to get optimal support. When submitting the ticket, please specify your AppsFlyer sign-up (account) email, app ID, reproduction steps, code snippets, logs, the links you used, and any additional relevant information.

onDeepLinking cannot obtain key information, such as media_ source

**Comment by RobertBrunhage** [comment]
We had forgotten adding the brand links

**Comment by spegoraro** [comment]
Hi there, I'm also experiencing this, can I ask what you did to get it working with short links?
