### ISSUE TITLE
Does plugin supports Google Play Install Referrer?

### ISSUE THREAD

**Issue by khurram72** [AppsFlyerSDK/appsflyer-flutter-plugin#191]
I can see the plugin have dependencies for AppFlyers native sdk and Google Play Install Referrer.

```
dependencies {
    implementation 'com.appsflyer:af-android-sdk:6.4.3'
    implementation 'com.android.installreferrer:installreferrer:2.1'
}
```

So, do we need to implement the Google Play Install Referrer in our flutter app's native android side?

Something suggested for android sdk integration here: https://developer.android.com/google/play/installreferrer/library

Please guide us on this.

If yes, a quick guide would be really helpful to us.

Thanks!

**Comment by af-fess** [comment]
There is no need for you to do anything. SDK already loads `com.android.installreferrer`
