### ISSUE TITLE
I can't get idfa

### ISSUE THREAD

**Issue by kimiangel** [AppsFlyerSDK/appsflyer-flutter-plugin#214]
appsFlyerOptions = {
        "afDevKey": "Tk3dHSbqN9kCcipfqBy2Ue",
        "afAppId": "1611120088",
        "isDebug": false,
        "disableAdvertisingIdentifier": false,
        "timeToWaitForATTUserAuthorization": 30
      };
Raw data downloaded from appsflyer's background
![image](https://user-images.githubusercontent.com/10664586/164954944-1f1b80ab-caaf-4bc7-9b5d-b0501f276f1d.png)

This is my initialization code but I keep getting no idfa

**Comment by pazlavi** [comment]
👋 Hi @kimiangel  and Thank you for reaching out to us.
In order for us to provide optimal support, please submit a ticket to our support team at [support@appsflyer.com](mailto:support@appsflyer.com).
When submitting the ticket, please specify:

✅ your AppsFlyer sign-up (account) email
✅ app ID
✅ production steps
✅ logs
✅ code snippets
✅ and any additional relevant information.
