### ISSUE TITLE
When we try to open onelink and app state is killed the link does not work on android and iOS

### ISSUE THREAD

**Issue by IsmailAAmassi** [AppsFlyerSDK/appsflyer-flutter-plugin#229]
When we try to open one link and the app state is killed the link does not work, but it works if the app is in the foreground on android and iOS onAppOpenAttribution callback not called

**Comment by pazlavi** [comment]
Hi @IsmailAAmassi,
Thank you for reaching out to us.
To provide optimal support, we would kindly ask you to submit a support ticket to support@appsflyer.com.

When submitting the ticket, please specify your AppsFlyer sign-up (account) email, app ID, reproduction steps, code snippets, logs, the links you used, and any additional relevant information.

**Comment by suphawutP** [comment]
I facing same this issue have any solution?

**Comment by af-do** [comment]
Hey @suphawutP,
As @pazlavi already said, to provide optimal support for issues like this, we would like to ask you to submit a support ticket to [support@appsflyer.com](mailto:support@appsflyer.com).

When submitting the ticket, please specify any information that is relevant to the issue you are facing; The AppsFlyer sign-up email, app ID, code snippets, logs, the links you've used, and anything else.

**Comment by suphawutP** [comment]
UPDATE: I have solve this issue in my project by place `appsflyerSdk?.initSdk` after `appsflyerSdk?.onInstallConversionData` and `appsflyerSdk?.onDeepLinking` now it's working for me. 
Hope this help.
