### ISSUE TITLE
Non organic install are not being showing up in the Dashboard

### ISSUE THREAD

**Issue by vaideheeVala** [AppsFlyerSDK/appsflyer-flutter-plugin#25]
i have user this sdk but it never shows non-orgainic installs , can you please tell me what might be the problem?

**Comment by GM-appsflyer** [comment]
Hey vaidehee,

In order to test the Non-organic install:

1. Please make sure that the device which is being used for the test is whitelisted (https://support.appsflyer.com/hc/en-us/articles/207031996--Whitelisting-a-test-device).

2. Create a link like:
iOS - https://app.appsflyer.com/<app_id>?pid=Test&c=Test&idfa=<IDFA>
Android - https://app.appsflyer.com/<app_id>?pid=Test&c=Test&advertising_id=<GAID>

3. Replace the following parameters:
    app_id - ID of the app that is being tested
    pid - media source name (for example “SDKTest”)
    c - campaign name
    IDFA/advertising_id - Advertising ID if the device used for the test

4. Send the link to the device by email (It is important to use email as we are aware of some limitations of other platforms and messengers that make affect test results)

5. Click on the link and install the app (If the app is not available in the store or doesn’t contain AppsFlyer SDK yet, you can install APK manually)

6. Check if the install was attributed as a Non-organic install on AppsFlyer Dashboard. If not, please send us full logs taken from the Xcode log debugger.

If you are still unable to generate a non-organic install please contact support@appsflyer.com, and we will be happy to help!

**Comment by rygalang** [comment]
Hi,

Any updates/resolution with this?

**Comment by GM-appsflyer** [comment]
Hey,

Thank you for contacting us!

I'm not sure I understand what is the issue.
Please open a support ticket so we could further debug: support@appsflyer.com
Make sure to send us full logs (while our [debug mode is enabled](https://support.appsflyer.com/hc/en-us/articles/360001559405-Testing-AppsFlyer-SDK-integration#debugging))

Thank you!

**Comment by wangxingxing123654** [comment]
I/AppsFlyer_5.4.5( 9796): ******* sendTrackingWithEvent: Launch
W/AppsFlyer_5.4.5( 9796): Exception while collecting facebook's attribution ID.
I/AppsFlyer_5.4.5( 9796): IMEI was not collected.
I/AppsFlyer_5.4.5( 9796): Android ID was not collected.
I/AppsFlyerOaid5.4.4( 9796): Fetch 1 ms
D/AppsFlyer_5.4.5( 9796): AppsFlyer: first launch detected
I/AppsFlyer_5.4.5( 9796): AppsFlyer: first launch date: 2020-11-19_125442+0000
W/AppsFlyer_5.4.5( 9796): Cannot verify existence of our InstanceID Listener Service in the manifest. Please refer to documentation.
D/AppsFlyer_5.4.5( 9796): didConfigureTokenRefreshService=false
D/AppsFlyer_5.4.5( 9796): No deep link detected
I/AppsFlyer_5.4.5( 9796): AppsFlyerLib.sendTrackingWithEvent
D/AppsFlyer_5.4.5( 9796): Install referrer is allowed

**Comment by GM-appsflyer** [comment]
Hey!
Did you manage to resolve the issue?

**Comment by fedorstepanovv** [comment]
Did someone solve this issue? I have the same. Try to init sdk via future builder to finally start tracking installs, but there aren't any numbers in my dashboard.

**Comment by nsleche** [comment]
The only thing that worked for me was installing this [app by AppsFlyer][1] and registering a new device with the IDFA displayed on the app. After that I was able to verify the non-organic installs, either testing from the [dashboard][2] or the [docs way][3]


  [1]: https://apps.apple.com/app/id1192323960
  [2]: https://hq1.appsflyer.com/sdk-integration-test/app/
  [3]: https://dev.appsflyer.com/hc/docs/testing-ios

**Comment by PramilaHJoshi** [comment]
I am not able get non-organic installs any suggestions

**Comment by anibalbastiass** [comment]
Hey. I'm stuck in this same issue. Do you have a documentation about how to test Non-organic events for debug apps?

**Comment by NesanSelvan** [comment]
@nsleche Thanks, it worked!
For those who are unable to get non-organic installs, try adding your device ID to the testing devices. For me in android, I added the IMEI number initially, and it was showing organic installs. Later, I replaced the IMEI with the AID, and then the non-organic installs started showing up.

**Comment by anibalbastiass** [comment]
> @nsleche Thanks, it worked! For those who are unable to get non-organic installs, try adding your device ID to the testing devices. For me in android, I added the IMEI number initially, and it was showing organic installs. Later, I replaced the IMEI with the AID, and then the non-organic installs started showing up.

I got the same solution a few months ago! Thanks for share this.

**Comment by one1color** [comment]
I have registered my device ID as testing devices, but still doesn't work. Anybody is still struggled with this?

**Comment by NesanSelvan** [comment]
> I have registered my device ID as testing devices, but still doesn't work. Anybody is still struggled with this?

Have you added your device AID to the list of testing devices?

**Comment by one1color** [comment]
Yes I got my IDFA from appsflyer app, and registered this to the list of test device. Is there anything I should look into?

**Comment by hnguyen-mwb** [comment]
For me, I do factory reset phone in case iOS device, install device id AppsFlyer app, register phone, check on AppsFlyer testing device if the phone is on the list, then install app from onelink and I can see non-organic installation
