### ISSUE TITLE
NullPointerException Attempt to invoke virtual method 'android.content.Context android.content.Context.getApplicationContext()' on a null object reference

### ISSUE THREAD

**Issue by felipe-xavier** [AppsFlyerSDK/appsflyer-flutter-plugin#250]
We are facing an issue of Null-Pointer-Exception when the SDK is initialized on Android

Sentry Logs:
<img width="1207" alt="Screenshot 2023-01-10 at 20 47 06" src="https://user-images.githubusercontent.com/11222002/211648038-f6c20cad-4623-48a1-8cc6-d1b850fa4fb3.png">

Code snippets:
<img width="216" alt="main" src="https://user-images.githubusercontent.com/11222002/211639595-7961b9cf-8eac-46f4-8c88-98847aa8c3b0.png">

<img width="661" alt="appsflyer-init" src="https://user-images.githubusercontent.com/11222002/211639598-63737cb6-002f-4169-8252-4ddfd7945254.png">

We initialize AppsFlyer though our `initAppsflyer` method called in `Main` right before `runApp` method is called.

According to Sentry, this issue happens only on Android and on production so far, and started happening after we added the `just_audio` package with `audio_session` to reproduce audio in the background, but since we are getting logs with errors when initialising AppsFlyer, we are writing to you for help.

We saw that there is [this PR](https://github.com/AppsFlyerSDK/appsflyer-flutter-plugin/pull/205) that tried to solve a similar issue even mentioning audio_session package, but was never approved or discussed. 

So we would like to know if this issue has been noticed by the AppsFlyer SDK team and if a solution has been found.

Please, let us know if you can help us.

**Comment by dmontil** [comment]
Same issue

**Comment by minoesteban** [comment]
Same issue

**Comment by GM-appsflyer** [comment]
plugin fix for this issue was released on v6.11.3
