### ISSUE TITLE
403 Error Code - Forbidden

### ISSUE THREAD

**Issue by dnzzcn** [AppsFlyerSDK/appsflyer-flutter-plugin#254]
We added the package to our flutter project. We correctly set up the sdk with correct dev key and app id. However, we cannot use the service since all of our attempts results in 403 message. 

Here is the error report returned after the sdk sends the first message:

Result: {
    data = {length = 9, bytes = 0x666f7262696464656e};
    dataStr = forbidden;
    retries = 0;
    statusCode = 403;
    taskIdentifier = 3;
}

There is not much to talk about really, there are 6 lines of codes and the sdk doesn't work. What do we do?

**Comment by swiftymf** [comment]
I'm also having this issue after having used AppsFlyer for some time. Can someone look into this?

**Comment by mkobuolys** [comment]
This is expected when using the free (Zero) plan: https://dev.appsflyer.com/hc/docs/testing-android#i-get-response-403-on-install-or-event-recording

I would suggest closing the issue.

**Comment by fullflash** [comment]
we were able to use in development and did not publish yet the app wth this sdk and suddenly 
we start to get error on startSdk method and there is no error descption just 403 error code 
i dont understand what is the point to enableding debugMode if the sdk not able to provide a normal error description.
i did not see in docusments about zero plan trial period to use sdk.
