### ISSUE TITLE
Uninstall not recorded

### ISSUE THREAD

**Issue by arlakay** [AppsFlyerSDK/appsflyer-flutter-plugin#26]
Uninstall metrics not recorded on dashboard

**Comment by af-fess** [comment]
Can you give more details about the problem? The platform, what did you try so far?

**Comment by ShaharAF** [comment]
Did you use `updateServerUninstallToken`?  the function `enableUninstallTracking` isn't working anymore

**Comment by arlakay** [comment]
I call both function , on version 1.2.1 & 1.2.2 and not recorded.

**Comment by shahar3** [comment]
@arlakay please contact support@appsflyer.com, and we will be happy to help you with solving this issue
