### ISSUE TITLE
enableUninstallTracking is missing

### ISSUE THREAD

**Issue by victorhugo963** [AppsFlyerSDK/appsflyer-flutter-plugin#27]
why the following methods are commented?

AppsflyerSdkPlugin.m 
lse if([@"enableUninstallTracking" isEqualToString:call.method]){
        //
}

AppsflyerSdkPlugin.java
// private void enableUninstallTracking(MethodCall call, Result result) {
//     String senderId = (String) call.argument("senderId");
//     AppsFlyerLib.getInstance().enableUninstallTracking(senderId);
//     result.success(null);
// }

however the method call is in the appsflyer_sdk.dart

void enableUninstallTracking(String senderId) {
    _methodChannel
        .invokeMethod("enableUninstallTracking", {'senderId': senderId});
  }

**Comment by ShaharAF** [comment]
Hi @victorhugo963, thank you for opening this issue.
From AppsFlyer SDK 5.0.0+ we no longer use this method to track uninstall.
Instead of that we use `updateServerUninstallToken(String token)`.
I've left this function open because I didn't want to break any app that already use this function to track.

I will add a log print that will inform that this function no longer available and you need to switch to `updateServerUninstallToken`.

**Comment by rekor-dev** [comment]
Hi @ShaharAF may I ask for help ?
how to implement "updateServerUninstallToken" in flutter ?
I don't find in example code.

**Comment by victorhugo963** [comment]
Hello Erwan, in my application I'm using the firebase token, so every time
I call updateServerUninstallToken, I pass the token in the parameter.

static updateServerUninstallToken() async {
SharedPreferencesService _prefs = SharedPreferencesService();
try {
_prefs.getTokenFirebase().then((token) {
if (token != null) {
_appsFlyerSdk.updateServerUninstallToken(token);
}
});
} catch (e) {
print('Error appsflyer: $e');
}
}

Best Regards,
Victor Hugo Batista da Silva


Em ter., 8 de set. de 2020 às 08:32, Erwan <notifications@github.com>
escreveu:

**Comment by rekor-dev** [comment]
Hi Victor, 

Thank you for your quick response. 
So when we call updateServerUninstallToken() function?
but how Appsflyer knows that our app was uninstalled, I still don't understand.

Best Regards,
Erwan

**Comment by victorhugo963** [comment]
I also never knew for sure how it recognizes the uninstallation, but I
believe it has to do with the device's token, every time a new installation
changes the token completely, recognizing a new uninstallation, I call this
function every time I start the appsflyer.

Em ter., 8 de set. de 2020 às 09:38, Erwan <notifications@github.com>
escreveu:
