### ISSUE TITLE
New release required due to crashes bug fix in Android SDK

### ISSUE THREAD

**Issue by roblframpton** [AppsFlyerSDK/appsflyer-flutter-plugin#282]
[A bug causing app crashes on rooted phones](https://github.com/AppsFlyerSDK/appsflyer-android-app/issues/20) has recently been fixed in the Android SDK and [released as version 6.12.2](https://central.sonatype.com/artifact/com.appsflyer/af-android-sdk/6.12.2).  Could a new version of the Flutter SDK please be released to include this fix?  The bug is causing full crashes of our app so I believe it is relatively critical.

**Comment by wordlesser** [comment]
Is there no official support?

**Comment by roblframpton** [comment]
It looks like this has now been [resolved](https://github.com/AppsFlyerSDK/appsflyer-flutter-plugin/commit/e8c4f04f0f94f419752c58b2d20ba5c521d25f43) and [released](https://pub.dev/packages/appsflyer_sdk/changelog).  Just no communication from the team about it 😅
