### ISSUE TITLE
Unhandled Exception: 'package:appsflyer_sdk/src/appsflyer_sdk.dart': Failed assertion: line 82 pos 14: 'exp.hasMatch(appID)': is not true.

### ISSUE THREAD

**Issue by devfunmilayor** [AppsFlyerSDK/appsflyer-flutter-plugin#283]
:dart_vm_initializer.cc(41)] Unhandled Exception: 'package:appsflyer_sdk/src/appsflyer_sdk.dart': Failed assertion: line 82 pos 14: 'exp.hasMatch(appID)': is not true.
package:appsflyer_sdk/src/appsflyer_sdk.dart:82
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      AppsflyerSdk._validateAFOptions
package:appsflyer_sdk/src/appsflyer_sdk.dart:82
#3      AppsflyerSdk.initSdk.<anonymous closure>
package:appsflyer_sdk/src/appsflyer_sdk.dart:160
<asynchronous suspension>
#4      AppflyerService.init
package:Grip/services/appflyer_service.dart:26
<asynchronous suspension>
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: 'package:appsflyer_sdk/src/appsflyer_sdk.dart': Failed assertion: line 82 pos 14: 'exp.hasMatch(appID)': is not true.
package:appsflyer_sdk/src/appsflyer_sdk.dart:82
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      AppsflyerSdk._validateAFOptions
package:appsflyer_sdk/src/appsflyer_sdk.dart:82
#3      AppsflyerSdk.initSdk.<anonymous closure>
package:appsflyer_sdk/src/appsflyer_sdk.dart:160
<asynchronous suspension>

**Comment by devfunmilayor** [comment]
Thank you, I will do that.

**Comment by danbeechbloom** [comment]
Any updates on this issue? I'm also getting this error when trying to integrate iOS.

**Comment by devfunmilayor** [comment]
Nothing yet

**Comment by danbeechbloom** [comment]
@devfunmilayor remove `id` from the beginning of the app ID you get from the dashboard. 
The error is caused by this regex not finding a match because the appId exceeds the char length:`RegExp exp = RegExp(r'^\d{8,11}$');`

@pazlavi could just strip `id` from the beginning of the string and this issue wouldn't crop up again? ☝️

**Comment by AkaankshK** [comment]
Removing id in the beginning resolved the issue for me. This should be mentioned or handled in the sdk.

**Comment by devfunmilayor** [comment]
Thank you all .
