### ISSUE TITLE
No start() function

### ISSUE THREAD

**Issue by jbankz** [AppsFlyerSDK/appsflyer-flutter-plugin#286]
**Describe the bug**
I am facing an issue where i am unable to complete the steps described in step 4 [here](https://support.appsflyer.com/hc/en-us/articles/207447103-Mixpanel-integration-with-AppsFlyer) integrating with mixpanel

**To Reproduce**
1. Go to [here](https://support.appsflyer.com/hc/en-us/articles/207447103-Mixpanel-integration-with-AppsFlyer)

**Expected behavior**
Expected to sync up with mixpanel after setting the users customer id setCustomerId

**Additional context**
https://support.appsflyer.com/hc/en-us/articles/207447103-Mixpanel-integration-with-AppsFlyer#integrating-with-mixpanel-when-using-a-login-mechanism

**Comment by al-af** [comment]
New startSDK API is introduced in flutter plugin v6.13.0+1
