### ISSUE TITLE
AppsflyerConstants.AF_VALIDATE_PURCHASE value spelling incorrectly

### ISSUE THREAD

**Issue by LSFMint** [AppsFlyerSDK/appsflyer-flutter-plugin#30]
**Describe the bug**
Kindly check the AppsflyerConstants.AF_VALIDATE_PURCHASE = "validePurchase" spelling  incorrectly. It causes the "_registerPurchaseValidateListener" cannot return correct result.

Expected value should be "validatePurchase".

**Comment by ShaharAF** [comment]
Thanks for opening this issue, will fix it 👍
