### ISSUE TITLE
iOS privacy manifest

### ISSUE THREAD

**Issue by yukihiro-numata** [AppsFlyerSDK/appsflyer-flutter-plugin#304]
By Apple's guidelines, you must add an empty file even if you are not collecting anything.
ref: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

**Comment by Heech** [comment]
Looks like the Apple privacy manifest support has yet to be added to the native iOS SDK.
https://support.appsflyer.com/hc/en-us/articles/115001224823-AppsFlyer-iOS-SDK-release-notes

This article says we can add the required reasons directly to the app's manifest until this is added in the SDK.
https://support.appsflyer.com/hc/en-us/articles/21677433322641-Privacy-Manifest

> AppsFlyer is working on an updated SDK which will include a Privacy Manifest to ease the app developers process of generating their nutrition labels - This SDK update is not mandatory.

> If you don't want to wait for the new SDK, you can declare the three required reasons APIs below using the provided code snippet in your Privacy Manifest.

**Comment by yukihiro-numata** [comment]
@snipd-min 
> could you clarify where it is implied that an empty file is needed even there is nothing to declare? I couldn't find it in the docs...

https://github.com/flutter/flutter/issues/139761#issuecomment-1881394943
In the above comment, it states that an empty file is needed even if there is nothing to declare.

However, I've found the comment also states that an empty file is not necessary when there are no declarations required.
> If your framework doesn't require a privacy manifest, do nothing. Avoid adding an empty privacy manifest to your framework.

ref: https://developer.apple.com/forums/thread/746481?answerId=782256022#782256022

So, I'm confused and unsure which information is correct.

**Comment by Danyalo** [comment]
Hello @al-af it seems that native iOS plugin already has privacy manifest support. Given that the deadline Apple gives for this is end of April, could you please roll out an updated Flutter package so we can start testing it?

**Comment by BenjaminStoeberl** [comment]
Any update on this? When do you plan do integrate the iOS SDK 6.14.0 into the flutter plugin?

**Comment by al-af** [comment]
@Danyalo @BenjaminStoeberl 
A new Flutter SDK version has been released v6.14.2, it's based on Android v6.14.0 and iOS v6.14.2 with the Privacy Manifest.
