### ISSUE TITLE
flutter build apk error

### ISSUE THREAD

**Issue by long51xy** [AppsFlyerSDK/appsflyer-flutter-plugin#31]
flutter build apk

Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      13.5s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin appsflyer_sdk...
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                    2.0s

FAILURE: Build failed with an exception.

Task 'assembleAarRelease' not found in root project 'appsflyer_sdk'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run wit
* Get more help at https://help.gradle.org

BUILD FAILED in 1s

The plugin appsflyer_sdk could not be built due to the issue above.
Could not find an option named "debu".

**Comment by GM-appsflyer** [comment]
Please reach out if you still encounter this issue :)

**Comment by andreferreiravntrs** [comment]
How did you solve this issue? I am facing the same problem
