### ISSUE TITLE
Can I  set deep_link_value with generateInviteLink method?

### ISSUE THREAD

**Issue by whtjtjddn** [AppsFlyerSDK/appsflyer-flutter-plugin#317]
I want to send dynamic value with onelink

```
AppsFlyerInviteLinkParams(
                    baseDeepLink: baseDeepLink,
                    customParams: {
                      "deep_link_value": params["link"],});
```
but I cannot set deepLinkValue with AppsFlyerInviteLinkParams (because of deferred deep linking)
Is it can just on Webpage with edit link?

**Comment by danReynolds** [comment]
What was the solution here?
