### ISSUE TITLE
There is a problem with the initSdk when  new AppsflyerSdk(Map options)

### ISSUE THREAD

**Issue by anan5520** [AppsFlyerSDK/appsflyer-flutter-plugin#318]
An error will be reported when running this code ：
![2511714107111_ pic](https://github.com/AppsFlyerSDK/appsflyer-flutter-plugin/assets/16335199/7f59a422-9c77-4233-b144-8eea8bde00d4)
AppsflyerSdk(AppsFlyerOptions options)  is no problem

**Comment by bekzat91** [comment]
same problem. For Android we pass a mapOptions, so checking for afOptions fails. Pls fix

**Comment by al-af** [comment]
Hey guys,
Thanks for mentioning it, it was fixed in v6.14.3
