### ISSUE TITLE
Does appsflyer flutter sdk supports the google play install referrer API ??

### ISSUE THREAD

**Issue by AhmadIzaz** [AppsFlyerSDK/appsflyer-flutter-plugin#330]
I see that there is a guide on how to install the Google Play install referrer here: [Basic SDK Integration Guide](https://support.appsflyer.com/hc/en-us/articles/207032066-Basic-SDK-integration-guide#attribute-apps-published-on-google-play).

I understand that this is an Android guide. My question is: Do I need to implement it in my flutter project through method channels for AppsFlyer to support the install referrer?

Is there any documentation available for Flutter? I read through the entire guide and couldn't find any helpful links on how to implement the install referrer for AppsFlyer so we can use that data.

P.S.: I know how to implement the install referrer through method channels or through Flutter pub dev, but I need to know how to send that data to AppsFlyer. Additionally, does the Flutter SDK for AppsFlyer handle this automatically, or am I missing something? I hope this makes sense.

**Comment by AhmadIzaz** [comment]
When I download this github repo to make sure either this sdk have the install referrer handled or not. I can see that this sdk have implemented the **instalreferrer:2.1**  but there is no such code as this in this repo 

`private lateinit var referrerClient: InstallReferrerClient

referrerClient = InstallReferrerClient.newBuilder(this).build()
referrerClient.startConnection(object : InstallReferrerStateListener {

    override fun onInstallReferrerSetupFinished(responseCode: Int) {
        when (responseCode) {
            InstallReferrerResponse.OK -> {
                // Connection established.
            }
            InstallReferrerResponse.FEATURE_NOT_SUPPORTED -> {
                // API not available on the current Play Store app.
            }
            InstallReferrerResponse.SERVICE_UNAVAILABLE -> {
                // Connection couldn't be established.
            }
        }
    }

    override fun onInstallReferrerServiceDisconnected() {
        // Try to restart the connection on the next request to
        // Google Play by calling the startConnection() method.
    }
})`

**Comment by AhmadIzaz** [comment]
Also when I run my app it shows me these logs of referrer 
![image](https://github.com/user-attachments/assets/efd0d602-e729-4922-b49a-7c257b19d5a4)

**Comment by AhmadIzaz** [comment]
@pazlavi its just a question, I don't need any support for now. My question is simple either this sdk is handling the google play install referrer on its own or not ? I don't want to be in a line of hundreds in the support. it will be just a waste of time.

**Comment by AhmadIzaz** [comment]
??

**Comment by ge-af** [comment]
Hi @AhmadIzaz 

Once the Google Play Install Referrer dependency is available (and it's being added by default in the Flutter plugin) we will try to collect the referrer data internally inside the native Android SDK. There is no need to add any extra code for it on your side.

From the debug logs you shared above it does seem like the Install Referrer logic is enabled and everything is working properly.

If you have any further comments or questions, please make sure to submit a ticket to our Support team at support@appsflyer.com and we will be more than happy to provide any additional assistance required.

**Comment by AhmadIzaz** [comment]
Thank you so much @ge-af for the response. Much appreciated to confirm this thing. is it possible to add this in documentation as well for future references. Thanks again :)
