### ISSUE TITLE
NullPointerException 

### ISSUE THREAD

**Issue by hnvmeta** [AppsFlyerSDK/appsflyer-flutter-plugin#347]
I have meet crash when I open app again after pressing back button to exit app. Google Play Store rejected my app update because of this issue.
SDK version: ^6.15.1
java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object)' on a null object reference
E/AndroidRuntime( 4410): 	at com.appsflyer.appsflyersdk.AppsflyerSdkPlugin$5$2.run(AppsflyerSdkPlugin.java:402)

**Comment by Dani-Koza-AF** [comment]
Fixed on v6.15.2 , please use this version :pray:
