### ISSUE TITLE
please perfect  your ReadMe doc

### ISSUE THREAD

**Issue by terge** [AppsFlyerSDK/appsflyer-flutter-plugin#35]
the read me doc just some API
the key info: such as when init af sdk,  i dont know
does it mean, i can init it whenever i like?  just ensure  the init action before  i use af?
the example exist the same problem, just told us how to use api
But When ,and the best practice , I dont know

**Comment by whatamelon** [comment]
agree.
Appsflyer's readme is too hard to understand.
What I want is use deep link with appsflyer, but I cant understand how I use it. 
So, I want you guys make readme doc clear.

**Comment by shredding** [comment]
It's horrible, really really horrible.

**Comment by okayfine** [comment]
Hi, can someone send me an example on how you guys implemented it? I can't seem to understand the part about 
`import 'package:appsflyer_sdk/appsflyer_sdk.dart';
//..

AppsflyerSdk _appsflyerSdk = AppsflyerSdk({...});

FutureBuilder<dynamic> ( future: _appsflyerSdk.initSdk(registerConversionDataCallback: true, registerOnAppOpenAttributionCallback: true), builder: (BuildContext context, AsyncSnapshot snapshot) {
  if (snapshot.hasData)
    return  HomeContainer(
      onData: _appsflyerSdk.conversionDataStream,
      onAttribution: _appsflyerSdk.appOpenAttributionStream,
      ...
    )
  ...`

**Comment by ShaharAF** [comment]
I've changed the README file and added more relevant examples. For full working implementation you can see the example app in this repository
