### ISSUE TITLE
com.appsflyer.appsflyersdk.AppsflyerSdkPlugin$5$2.run(AppsflyerSdkPlugin.java:402)

### ISSUE THREAD

**Issue by Shubhpreet-Rana** [AppsFlyerSDK/appsflyer-flutter-plugin#350]
**Describe the bug**
 java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object)' on a null object reference
E/AndroidRuntime(12164):        at com.appsflyer.appsflyersdk.AppsflyerSdkPlugin$5$2.run(AppsflyerSdkPlugin.java:402)
E/AndroidRuntime(12164):        at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(12164):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(12164):        at android.os.Looper.loop(Looper.java:201)
E/AndroidRuntime(12164):        at android.app.ActivityThread.main(ActivityThread.java:6810)
E/AndroidRuntime(12164):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12164):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/AndroidRuntime(12164):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**To Reproduce**
1. Exit the by pressing the back button (SystemNavigator.pop() or exit(1))
2. Click on app Icon or open from recent
3. App crashes
4. Repeat this process , will get erro in first or second attempt

**Expected behavior**
Open the app from start

**Comment by rohnsht** [comment]
I get the same issue.. Could you please fix this asap please?

**Comment by Dani-Koza-AF** [comment]
Fixed on v6.15.2 , please use this version :pray:
