### ISSUE TITLE
social parameters in deeplink

### ISSUE THREAD

**Issue by nazarcybulskij** [AppsFlyerSDK/appsflyer-flutter-plugin#359]
Hello,

I’m working on a project where I need to create a deeplink in appsflyerSdk that includes socialMetaTagParameters. My goal is to add parameters like title, description, and image to enhance the link preview when it’s shared on social media. However, I haven’t found any examples or documentation explaining how to implement this.

Could you please advise if this feature is supported in appsflyerSdk, and if so, how to implement socialMetaTagParameters for a deeplink?

Thank you very much for your assistance!

Best regards,
Nazar Cybulski

**Comment by nazarcybulskij** [comment]
st	af_og_title	Used to customize the title of shared content on Social media
sd	af_og_description	Used to customize the description of shared content on social media
si	af_og_image	Used to customize the image of shared content on social media     --   I found this in documentation  -- it is work for me.

**Comment by fullflash** [comment]
> st af_og_title Used to customize the title of shared content on Social media sd af_og_description Used to customize the description of shared content on social media si af_og_image Used to customize the image of shared content on social media -- I found this in documentation -- it is work for me.

can you provide an example how to achieve this using this flutter plugin

there is a method for plugin and for method argument `AppsFlyerInviteLinkParams` there is no such a social tag properties
we tried to add af_og_title and af_og_image to customParams map but with no success.
`generateInviteLink`
