### ISSUE TITLE
Example on android do not send data

### ISSUE THREAD

**Issue by marinat** [AppsFlyerSDK/appsflyer-flutter-plugin#36]
On ios all ok, on android i've got errors:

`E/AppsFlyer_5.4.1(11248): Failed resolution of: Lcom/google/android/gms/common/GoogleApiAvailability;
E/AppsFlyer_5.4.1(11248): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/GoogleApiAvailability;
E/AppsFlyer_5.4.1(11248): 	at com.appsflyer.internal.v.ι(:65)
E/AppsFlyer_5.4.1(11248): 	at com.appsflyer.AppsFlyerLibCore.ɩ(:1766)
E/AppsFlyer_5.4.1(11248): 	at com.appsflyer.AppsFlyerLibCore.Ι(:1603)
E/AppsFlyer_5.4.1(11248): 	at com.appsflyer.AppsFlyerLibCore.ι(:99)
E/AppsFlyer_5.4.1(11248): 	at com.appsflyer.AppsFlyerLibCore$e.run(:3307)
E/AppsFlyer_5.4.1(11248): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
E/AppsFlyer_5.4.1(11248): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AppsFlyer_5.4.1(11248): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
E/AppsFlyer_5.4.1(11248): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AppsFlyer_5.4.1(11248): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AppsFlyer_5.4.1(11248): 	at com.appsflyer.AFExecutor$1$1.run(:31)
E/AppsFlyer_5.4.1(11248): 	at java.lang.Thread.run(Thread.java:919)
E/AppsFlyer_5.4.1(11248): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.GoogleApiAvailability" on path: DexPathList[[zip file "/data/app/com.appsflyer.appsflyersdkexample-UpFCLAqFexRxa--C6g3IWQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.appsflyer.appsflyersdkexample-UpFCLAqFexRxa--C6g3IWQ==/lib/arm64, /data/app/com.appsflyer.appsflyersdkexample-UpFCLAqFexRxa--C6g3IWQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
E/AppsFlyer_5.4.1(11248): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
E/AppsFlyer_5.4.1(11248): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AppsFlyer_5.4.1(11248): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AppsFlyer_5.4.1(11248): 	... 12 more
E/AppsFlyer_5.4.1(11248): com.google.android.gms.ads.identifier.AdvertisingIdClient
E/AppsFlyer_5.4.1(11248): java.lang.ClassNotFoundException: com.google.android.gms.ads.identifier.AdvertisingIdClient
E/AppsFlyer_5.4.1(11248): 	at java.lang.Class.classForName(Native Method)
E/AppsFlyer_5.4.1(11248): 	at java.lang.Class.forName(Class.java:454)
E/AppsFlyer_5.4.1(11248): 	at java.lang.Class.forName(Class.java:379)
E/AppsFlyer_5.4.1(11248): 	at com.appsflyer.internal.v.ι(:70)
E/AppsFlyer_5.4.1(11248): 	at com.appsflyer.AppsFlyerLibCore.ɩ(:1766)
E/AppsFlyer_5.4.1(11248): 	at com.appsflyer.AppsFlyerLibCore.Ι(:1603)
E/AppsFlyer_5.4.1(11248): 	at com.appsflyer.AppsFlyerLibCore.ι(:99)
E/AppsFlyer_5.4.1(11248): 	at com.appsflyer.AppsFlyerLibCore$e.run(:3307)
E/AppsFlyer_5.4.1(11248): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
E/AppsFlyer_5.4.1(11248): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AppsFlyer_5.4.1(11248): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
E/AppsFlyer_5.4.1(11248): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AppsFlyer_5.4.1(11248): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AppsFlyer_5.4.1(11248): 	at com.appsflyer.AFExecutor$1$1.run(:31)
E/AppsFlyer_5.4.1(11248): 	at java.lang.Thread.run(Thread.java:919)
E/AppsFlyer_5.4.1(11248): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.identifier.AdvertisingIdClient" on path: DexPathList[[zip file "/data/app/com.appsflyer.appsflyersdkexample-UpFCLAqFexRxa--C6g3IWQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.appsflyer.appsflyersdkexample-UpFCLAqFexRxa--C6g3IWQ==/lib/arm64, /data/app/com.appsflyer.appsflyersdkexample-UpFCLAqFexRxa--C6g3IWQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
E/AppsFlyer_5.4.1(11248): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
E/AppsFlyer_5.4.1(11248): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AppsFlyer_5.4.1(11248): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AppsFlyer_5.4.1(11248): 	... 15 more
I/AppsFlyer_5.4.1(11248): WARNING: Google Play Services is missing.`

I used Pixel 2 and example project with my afDevKey.

**Comment by scullabyte** [comment]
Same here. Works on an ios phone for me, then when I compile on android it stops working.

**Comment by marinat** [comment]
Updated to latest version and got:
`I/AppsFlyer_5.4.3(10417): ******* sendTrackingWithEvent: CompleteRegistration
W/AppsFlyer_5.4.3(10417): Exception while collecting facebook's attribution ID. 
I/AppsFlyer_5.4.3(10417): IMEI was not collected.
I/AppsFlyer_5.4.3(10417): Android ID was not collected.
I/AppsFlyerOaid5.4.2(10417): Failed resolution of: Lcom/bun/miitmdid/core/JLibrary;
I/AppsFlyerOaid5.4.2(10417): Fetch 1 ms
I/AppsFlyer_5.4.3(10417): AppsFlyer: first launch date: 2020-09-07_125839+0000
W/AppsFlyer_5.4.3(10417): Cannot verify existence of our InstanceID Listener Service in the manifest. Please refer to documentation.
D/AppsFlyer_5.4.3(10417): didConfigureTokenRefreshService=false
I/flutter (10417): Transition { currentState: ConfirmElapsed, event: StartConfirmTimer, nextState: ConfirmElapsed }
I/AppsFlyer_5.4.3(10417): AppsFlyerLib.sendTrackingWithEvent
I/AppsFlyer_5.4.3(10417): url: https://inapps.appsflyer.com/api/v5.4/androidevent?app_id=com.novakid.student&buildnumber=5.4.3
I/AppsFlyer_5.4.3(10417): data: {"country":"RU","af_timestamp":"1599485387139","appsflyerKey":"k********************m","af_events_api":"1","isFirstCall":"false","registeredUninstall":false,"cell":{"mnc":1,"mcc":250},"operator":"МТС","network":"WIFI","af_v2":"240a44921b7d26b70b9d84e758589afbcf8e6f80","sig":"99C2BCD080132CA8AE587873DD74A6F06AC2A458D962B9F242F600F7AC0562CF","uid":"1599483518655-432747489273701628","eventValue":"{\"userId\":6341}","isGaidWithGps":"true","lang_code":"ru","installDate":"2020-09-07_125827+0000","app_version_code":"26","firstLaunchDate":"2020-09-07_125839+0000","ivc":false,"eventName":"CompleteRegistration","model":"Pixel 2","lang":"русский","brand":"google","deviceType":"user","last_boot_time":1599328371064,"product":"walleye","deviceData":{"cpu_abi":"arm64-v8a","build_display_id":"QQ3A.200805.001","dim":{"size":"2","ydp":"443.345","xdp":"442.451","y_px":"1878","x_px":"1080","d_dpi":"420"},"arch":"","cpu_abi2":""},"date2":"2020-09-07_162725+0300","counter":"3","date1":"2020-09-07_155827+0300","advertiserId":"ef3083fd-6a34-44af-bf93-c9de46c3fb15","advertiserIdEnabled":"true","af_v":"1f8bd459795fa99643053db74cebbd839881b995","carrier":"MTS RUS","disk":"3235\/53316","kef6c65":"a651f11d1e0763cf4818181b0c531a0d5919130d5a1f1f","af_preinstalled":"false","iaecounter":"3","sc_o":"p","tokenRefreshConfigured":false,"sdk":"29","app_version_name":"2.0.10","device":"walleye","prev_event":"{\"prev_event_timestamp\":\"1599485345200\",\"prev_event_value\":\"{\\\"userId\\\":6341}\",\"prev_event_name\":\"Lead\"}","platformextension":"android_flutter","cksm_v1":"f9623c8484629f545f08bd351608df9ee5"}
D/AppsFlyer_5.4.3(10417): Exception in sendRequestToServer. 
I/AppsFlyer_5.4.3(10417): failed to send requeset to server. Failed to connect to inapps.appsflyer.com/0.0.0.0:443
D/AppsFlyer_5.4.3(10417): Exception while sending request to server. 
I/AppsFlyer_5.4.3(10417): caching request...
D/AppsFlyer_5.4.3(10417): Failed to connect to inapps.appsflyer.com/0.0.0.0:443`

**Comment by ShaharAF** [comment]
@scullabyte Can you verify if its working on the latest plugin version (with Android SDK v5.4.3)?

**Comment by marinat** [comment]
@ShaharAF Hi, i used my afDevKey in example application and got result:
![2020-09-22 13 38 19](https://user-images.githubusercontent.com/978076/93872497-edbddd00-fcd8-11ea-97df-4adcf7882c49.jpg)
![2020-09-22 13 38 15](https://user-images.githubusercontent.com/978076/93872502-ef87a080-fcd8-11ea-8749-878ac29cc801.jpg)

**Comment by marinat** [comment]
What about progress?

**Comment by marinat** [comment]
Tried new library version, I have new errors
![2020-10-26 12 47 55](https://user-images.githubusercontent.com/978076/97157720-82f53b00-1789-11eb-8aae-5b1c8b42a2b9.jpg)
Logs:
`Launching lib/main.dart on Pixel 2 in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Waiting for Pixel 2 to report its views...
Debug service listening on ws://127.0.0.1:57495/OGzpMuXQXPY=/ws
Syncing files to device Pixel 2...
D/AppsFlyer_5.4.5(20469): Install referrer is allowed
D/AppsFlyer_5.4.5(20469): Connecting to Install Referrer Library...
D/AppsFlyer_5.4.5(20469): Connecting to Install Referrer Library...
D/AppsFlyer_5.4.5(20469): Initializing AppsFlyer SDK: (v5.4.5.54)
I/AppsFlyer_5.4.5(20469): Sending first launch for this session!
I/AppsFlyer_5.4.5(20469): Starting AppsFlyer Tracking: (v5.4.5.54)
I/AppsFlyer_5.4.5(20469): sendTrackingWithEvent from activity: android.app.Application
I/AppsFlyer_5.4.5(20469): Build Number: 54
D/AppsFlyer_5.4.5(20469): Loading properties..
D/AppsFlyer_5.4.5(20469): Done loading properties: true
I/AppsFlyer_5.4.5(20469): appsflyer_backup_rules.xml detected, using AppsFlyer defined backup rules for AppsFlyer SDK data
I/AppsFlyer_5.4.5(20469): Trying to fetch GAID..
D/AppsFlyer_5.4.5(20469): Failed resolution of: Lcom/google/android/gms/common/GoogleApiAvailability;
D/AppsFlyer_5.4.5(20469): com.google.android.gms.ads.identifier.AdvertisingIdClient
I/AppsFlyer_5.4.5(20469): WARNING: Google Play Services is missing.
D/AppsFlyer_5.4.5(20469): InstallReferrer connected
I/AppsFlyer_5.4.5(20469): ******* sendTrackingWithEvent: Launch
W/AppsFlyer_5.4.5(20469): Exception while collecting facebook's attribution ID. 
D/AppsFlyer_5.4.5(20469): WARNING:  Google play services is unavailable. 
I/AppsFlyer_5.4.5(20469): IMEI was not collected.
D/AppsFlyer_5.4.5(20469): WARNING:  Google play services is unavailable. 
I/AppsFlyer_5.4.5(20469): Android ID was not collected.
I/AppsFlyerOaid5.4.4(20469): Fetch 1 ms
I/TetheringManager(20469): registerTetheringEventCallback:com.appsflyer.appsflyersdkexample
D/AppsFlyer_5.4.5(20469): Install Referrer collected locally
D/AppsFlyer_5.4.5(20469): Install Referrer collected locally
I/AppsFlyer_5.4.5(20469): AppsFlyer: first launch date: 2020-10-26_093247+0000
D/AppsFlyer_5.4.5(20469): didConfigureTokenRefreshService=false
D/AppsFlyer_5.4.5(20469): No deep link detected
I/AppsFlyer_5.4.5(20469): AppsFlyerLib.sendTrackingWithEvent
W/flyersdkexampl(20469): Accessing hidden method Landroid/app/ActivityThread;->currentApplication()Landroid/app/Application; (greylist, reflection, allowed)
W/flyersdkexampl(20469): Accessing hidden field Ldalvik/system/BaseDexClassLoader;->pathList:Ldalvik/system/DexPathList; (greylist, reflection, allowed)
W/flyersdkexampl(20469): Accessing hidden field Ldalvik/system/DexPathList;->nativeLibraryDirectories:Ljava/util/List; (greylist, reflection, allowed)
W/flyersdkexampl(20469): Accessing hidden field Ldalvik/system/DexPathList;->nativeLibraryPathElements:[Ldalvik/system/DexPathList$NativeLibraryElement; (greylist, reflection, allowed)
I/AppsFlyer_5.4.5(20469): url: https://launches.appsflyer.com/api/v5.4/androidevent?app_id=com.appsflyer.appsflyersdkexample&buildnumber=5.4.5
I/AppsFlyer_5.4.5(20469): data: {"country":"RU","af_timestamp":"1603705545679","appsflyerKey":"k********************m","af_events_api":"1","isFirstCall":"true","registeredUninstall":false,"cell":{"mnc":1,"mcc":250},"operator":"МТС","network":"WIFI","timepassedsincelastlaunch":"715","open_referrer":"","af_v2":"7c407d68cccc370f3e432a0dc21501da0fb3f9b2","sig":"FC108868BA52E43DE08AFE5675F143432AB2CFF7E9048B2A097C14E2B745EADA","uid":"1603704767497-3044346707748188913","isGaidWithGps":"false","lang_code":"ru","installDate":"2020-10-26_093112+0000","app_version_code":"1","firstLaunchDate":"2020-10-26_093247+0000","ivc":false,"model":"Pixel 2","lang":"русский","brand":"google","deviceType":"user","last_boot_time":1603123971471,"product":"walleye","deviceData":{"cpu_abi":"arm64-v8a","build_display_id":"RP1A.201005.004","btch":"ac","dim":{"size":"2","ydp":"443.345","xdp":"442.451","y_px":"1878","x_px":"1080","d_dpi":"420"},"arch":"","btl":"82.0","cpu_abi2":""},"date2":"2020-10-26_123112+0300","counter":"3","date1":"2020-10-26_123112+0300","advertiserId":"ef3083fd-6a34-44af-bf93-c9de46c3fb15","advertiserIdEnabled":"true","af_v":"fbc279e696dab387733d34602f29da5d2ee33d30","exception_number":23,"carrier":"MTS RUS","disk":"1288\/53316","af_preinstalled":"false","iaecounter":"1","sc_o":"p","tokenRefreshConfigured":false,"kef6d68":"6631c9d60b4da7034818131b0c531a0d5919130d5a1f1c","sdk":"30","gaidError":"-1: ClassNotFoundException |","app_version_name":"1.0.0","device":"walleye","platformextension":"android_flutter","cksm_v1":"4a9a2f23a08a8d868f15a4852ea93f6dc1"}
I/AppsFlyer_5.4.5(20469): response code: 400
D/AppsFlyer_5.4.5(20469): [GCD-A01] Loading conversion data. Counter: 3
I/AppsFlyer_5.4.5(20469): [GCD-B01] URL: https://gcdsdk.appsflyer.com/install_data/v4.0/com.appsflyer.appsflyersdkexample?devkey=k********************m&device_id=1603704767497-3044346707748188913
D/AppsFlyer_5.4.5(20469): [GCD-A02] Calling onConversionFailure with:
D/AppsFlyer_5.4.5(20469): Error connection to server: 400
D/AppsFlyer_5.4.5(20469): [GCD-A03] Server retrieving attempt finished
I/AppsFlyer_5.4.5(20469): sendTrackingWithEvent from activity: android.app.Application
I/AppsFlyer_5.4.5(20469): Trying to fetch GAID..
D/AppsFlyer_5.4.5(20469): Failed resolution of: Lcom/google/android/gms/common/GoogleApiAvailability;
D/AppsFlyer_5.4.5(20469): com.google.android.gms.ads.identifier.AdvertisingIdClient
I/AppsFlyer_5.4.5(20469): WARNING: Google Play Services is missing.
I/AppsFlyer_5.4.5(20469): ******* sendTrackingWithEvent: my event
W/AppsFlyer_5.4.5(20469): Exception while collecting facebook's attribution ID. 
D/AppsFlyer_5.4.5(20469): WARNING:  Google play services is unavailable. 
I/AppsFlyer_5.4.5(20469): IMEI was not collected.
D/AppsFlyer_5.4.5(20469): WARNING:  Google play services is unavailable. 
I/AppsFlyer_5.4.5(20469): Android ID was not collected.
I/AppsFlyerOaid5.4.4(20469): Fetch 0 ms
I/AppsFlyer_5.4.5(20469): AppsFlyer: first launch date: 2020-10-26_093247+0000
D/AppsFlyer_5.4.5(20469): didConfigureTokenRefreshService=false
I/AppsFlyer_5.4.5(20469): AppsFlyerLib.sendTrackingWithEvent
I/AppsFlyer_5.4.5(20469): url: https://inapps.appsflyer.com/api/v5.4/androidevent?app_id=com.appsflyer.appsflyersdkexample&buildnumber=5.4.5
I/AppsFlyer_5.4.5(20469): data: {"country":"RU","af_timestamp":"1603705556145","appsflyerKey":"k********************m","af_events_api":"1","isFirstCall":"true","registeredUninstall":false,"cell":{"mnc":1,"mcc":250},"operator":"МТС","network":"WIFI","af_v2":"5c880a136ecf223126aa47e690bc7429c1e2bd2f","sig":"FC108868BA52E43DE08AFE5675F143432AB2CFF7E9048B2A097C14E2B745EADA","uid":"1603704767497-3044346707748188913","eventValue":"{\"af_currency\":\"USD\",\"af_content_id\":\"id123\",\"af_revenue\":\"2\"}","isGaidWithGps":"false","lang_code":"ru","installDate":"2020-10-26_093112+0000","app_version_code":"1","firstLaunchDate":"2020-10-26_093247+0000","ivc":false,"eventName":"my event","model":"Pixel 2","lang":"русский","brand":"google","deviceType":"user","last_boot_time":1603123971471,"product":"walleye","deviceData":{"cpu_abi":"arm64-v8a","build_display_id":"RP1A.201005.004","dim":{"size":"2","ydp":"443.345","xdp":"442.451","y_px":"1878","x_px":"1080","d_dpi":"420"},"arch":"","cpu_abi2":""},"date2":"2020-10-26_123112+0300","counter":"3","date1":"2020-10-26_123112+0300","advertiserId":"ef3083fd-6a34-44af-bf93-c9de46c3fb15","advertiserIdEnabled":"true","af_v":"b6708c594180906d7fd5f196b9780d1490d366da","carrier":"MTS RUS","disk":"1285\/53316","sensors":{"er":"na"},"af_preinstalled":"false","iaecounter":"2","sc_o":"p","tokenRefreshConfigured":false,"kef616b":"a8075d168494b6564818131b0c531a0d5919130d5a1f1d","sdk":"30","gaidError":"-1: ClassNotFoundException |","app_version_name":"1.0.0","device":"walleye","prev_event":"{\"prev_event_timestamp\":\"1603704771892\",\"prev_event_value\":\"{\\\"af_currency\\\":\\\"USD\\\",\\\"af_content_id\\\":\\\"id123\\\",\\\"af_revenue\\\":\\\"2\\\"}\",\"prev_event_name\":\"my event\"}","platformextension":"android_flutter","cksm_v1":"7bb3f0730764d7e51f37b9f48860cfac29"}
I/AppsFlyer_5.4.5(20469): response code: 400
D/AppsFlyer_5.4.5(20469): [GCD-A01] Loading conversion data. Counter: 3
`

**Comment by marinat** [comment]
Fixed with last appsflyer library. In example project just use example ids:
DEV_KEY=7jKdYxdnYcbSQ5iWrGytWc
APP_ID=112233554%
