### ISSUE TITLE
non-organic unable to count

### ISSUE THREAD

**Issue by AndroidHJS** [AppsFlyerSDK/appsflyer-flutter-plugin#38]
D/AppsFlyer_5.4.3( 3912): Install referrer is not allowed
D/AppsFlyer_5.4.3( 3912): Initializing AppsFlyer SDK: (v5.4.3.50)
I/AppsFlyer_5.4.3( 3912): Sending first launch for this session!
I/AppsFlyer_5.4.3( 3912): Starting AppsFlyer Tracking: (v5.4.3.50)
I/AppsFlyer_5.4.3( 3912): Build Number: 50
I/AppsFlyer_5.4.3( 3912): appsflyer_backup_rules.xml detected, using AppsFlyer defined backup rules for AppsFlyer SDK data
I/AppsFlyer_5.4.3( 3912): sendTrackingWithEvent from activity: android.app.Application
I/AppsFlyer_5.4.3( 3912): Trying to fetch GAID..
D/AppsFlyer_5.4.3( 3912): Failed resolution of: Lcom/google/android/gms/common/GoogleApiAvailability;
D/AppsFlyer_5.4.3( 3912): com.google.android.gms.ads.identifier.AdvertisingIdClient
I/AppsFlyer_5.4.3( 3912): WARNING: Google Play Services is missing.
I/AppsFlyer_5.4.3( 3912): ******* sendTrackingWithEvent: Launch
I/AppsFlyer_5.4.3( 3912): Initialising KeyStore..
I/AppsFlyer_5.4.3( 3912): Creating a new key with alias: com.appsflyer,KSAppsFlyerId=1600001075578-3836234870645651066,KSAppsFlyerRICounter=0
W/AppsFlyer_5.4.3( 3912): Exception while collecting facebook's attribution ID.
D/AppsFlyer_5.4.3( 3912): WARNING:  Google play services is unavailable.
I/AppsFlyer_5.4.3( 3912): IMEI was not collected.
D/AppsFlyer_5.4.3( 3912): WARNING:  Google play services is unavailable.
I/AppsFlyer_5.4.3( 3912): Android ID was not collected.

**Comment by af-fess** [comment]
Can you provide more details?

**Comment by wangxingxing123654** [comment]
+1

**Comment by omar-mohamed** [comment]
Adding:
`   
 implementation "com.google.android.gms:play-services-ads-identifier:17.0.+"
`
in android's build.gradle fixed this for me.

**Comment by GM-appsflyer** [comment]
Regarding this warning: D/AppsFlyer_5.4.3( 3912): com.google.android.gms.ads.identifier.AdvertisingIdClient
Please try updating to the latest SDK version, the warning should be gone.

**Comment by Lingviston** [comment]
What does the `Exception while collecting facebook's attribution ID.` mean? How to address it?
