### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bun/supplier/IIdentifierListener;

### ISSUE THREAD

**Issue by gerzang** [AppsFlyerSDK/appsflyer-flutter-plugin#46]
Hello, I am using the appsflyer with the following versions:
**appsflyer_sdk: ^ 6.0.3 + 5
AppsFlyer SDK: (v5.4.3.50)**

The first time I run the project I get the following error in console

I/zygote64(31889): **Rejecting re-init on previously-failed class java.lang.Class<com.appsflyer.oaid.OaidClient$1>:** **java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bun/supplier/IIdentifierListener;**
I/zygote64(31889):   **at java.util.Map com.appsflyer.AppsFlyerLibCore.ɩ(com.appsflyer.AFEvent) (:50514)**
I/zygote64(31889):   **at void com.appsflyer.AppsFlyerLibCore.ι(com.appsflyer.AFEvent) (:1626)**
I/zygote64(31889):   **at void com.appsflyer.AppsFlyerLibCore.ǃ(com.appsflyer.AppsFlyerLibCore, com.appsflyer.AFEvent) (:102)**
I/zygote64(31889):   **at void com.appsflyer.AppsFlyerLibCore$b.run() (:3347)**
I/zygote64(31889):   **at java.lang.Object java.util.concurrent.Executors$RunnableAdapter.call() (Executors.java:457)**
I/zygote64(31889):   **at void java.util.concurrent.FutureTask.run() (FutureTask.java:266)**
I/zygote64(31889):   **at void java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run() (ScheduledThreadPoolExecutor.java:301)**
I/zygote64(31889):   at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1162)
I/zygote64(31889):   at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:636)
I/zygote64(31889):   **at void com.appsflyer.AFExecutor$3$3.run() (:31)**
I/zygote64(31889):   **at void java.lang.Thread.run() (Thread.java:784)**
I/zygote64(31889): **Caused by: java.lang.ClassNotFoundException: Didn't find class "com.bun.supplier.IIdentifierListener" on path: DexPathList[[zip file "/data/app/ec.tipti-xsOhqU9T5ub_7XXTfqaDow==/base.apk"],nativeLibraryDirectories=[/data/app/ec.tipti-xsOhqU9T5ub_7XXTfqaDow==/lib/arm64, /data/app/ec.tipti-xsOhqU9T5ub_7XXTfqaDow==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /product/lib64]]
I/zygote64(31889):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:93)**
I/zygote64(31889):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/zygote64(31889):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/zygote64(31889):   **at java.util.Map com.appsflyer.AppsFlyerLibCore.ɩ(com.appsflyer.AFEvent) (:50514)**
I/zygote64(31889):   **at void com.appsflyer.AppsFlyerLibCore.ι(com.appsflyer.AFEvent) (:1626)**
I/zygote64(31889):   **at void com.appsflyer.AppsFlyerLibCore.ǃ(com.appsflyer.AppsFlyerLibCore, com.appsflyer.AFEvent) (:102)**
I/zygote64(31889):   **at void com.appsflyer.AppsFlyerLibCore$b.run() (:3347)**
I/zygote64(31889):   **at java.lang.Object java.util.concurrent.Executors$RunnableAdapter.call() (Executors.java:457)**
I/zygote64(31889):   **at void java.util.concurrent.FutureTask.run() (FutureTask.java:266)**
I/zygote64(31889):   **at void java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run() (ScheduledThreadPoolExecutor.java:301)
I/zygote64(31889):   at void java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) (ThreadPoolExecutor.java:1162)**
I/zygote64(31889):   **at void java.util.concurrent.ThreadPoolExecutor$Worker.run() (ThreadPoolExecutor.java:636)**
I/zygote64(31889):   **at void com.appsflyer.AFExecutor$3$3.run() (:31)**
I/zygote64(31889):   **at void java.lang.Thread.run() (Thread.java:784)**

**When I rerun the project the error stops showing**

In my project I am using the following
Ubuntu 18.04.5 LTS
Flutter 1.22.0 
Dart 2.10.0
Android Studio 4.1

And the device that I use to run the project is the following. Huawei P10 lite, this has Android 8.1

Any idea why I get this error the first time I run the project?

**Comment by selvakumardreams** [comment]
+1

**Comment by ShaharAF** [comment]
Hi, Thanks for letting me know. 
This issue was fixed in 5.4.4
I will update the plugin soon

**Comment by af-fess** [comment]
#52
