### ISSUE TITLE
MethodChannel delivery error

### ISSUE THREAD

**Issue by a27919478** [AppsFlyerSDK/appsflyer-flutter-plugin#47]
The Flutter side method is inconsistent with the native receiving processing method

in Flutter:
![image](https://user-images.githubusercontent.com/19726808/96549101-9adc4300-12e1-11eb-9ffd-7c4125d0951c.png)

in Android:
![image](https://user-images.githubusercontent.com/19726808/96549020-77b19380-12e1-11eb-8f6a-453b2db0e06b.png)

in iOS:
![image](https://user-images.githubusercontent.com/19726808/96549003-72544900-12e1-11eb-8f1f-316fcd284f62.png)

**Comment by ShaharAF** [comment]
Thanks for opening the issue. 
Will fix that in next plugin version release
