### ISSUE TITLE
Conversion data callback reports all installs as organic

### ISSUE THREAD

**Issue by DohanKim** [AppsFlyerSDK/appsflyer-flutter-plugin#48]
In-organic installs (Facebook Ads) showing up on Appsflyer dashboard correctly,
but conversion data callback reports all installs as organic. 
(Tested only in Android)

```
final appsflyerSdk = AppsflyerSdk(AppsFlyerOptions(
  afDevKey: "MYDEVKEY",
  appId: Platform.isIOS ? "IOSKEY" : "ANDROIDKEY",
  showDebug: true,
));

  appsflyerSdk
      .initSdk(
    registerConversionDataCallback: true,
  )
      .then((_) {
    appsflyerSdk.conversionDataStream.listen((data) {
      logger.d(data);
      if (data != null) {
        amplitudeAnalytics.setUserProperties({"conversion_data": data});
      }
    });
  });
```

**Comment by ShaharAF** [comment]
Hi @DohanKim. Thank you for opening this issue.
For attribution issues please contact our support team: support@appsflyer.com

**Comment by GM-appsflyer** [comment]
Please reach out to us or support@appsflyer.com if you still need help on this matter!
