### ISSUE TITLE
How to track uninstall on IOS?

### ISSUE THREAD

**Issue by b5710546291** [AppsFlyerSDK/appsflyer-flutter-plugin#54]
updateServerUninstallToken(fcmToken) work for android but does it work on ios?

I don't know Objective-C but is there suppose to be some code inside? 

https://github.com/AppsFlyerSDK/appsflyer-flutter-plugin/blob/5d01e095cb6db4223d2b9800636c46140c543007/ios/Classes/AppsflyerSdkPlugin.m#L275-L277

**Comment by af-fess** [comment]
hi @b5710546291 
yes, we are going to release a new version with this fix today-tomorrow
Thank you,

**Comment by b5710546291** [comment]
Does fcmtoken work or do we need apns to pass in updateServerUninstallToken?

**Comment by af-fess** [comment]
@b5710546291 you should pass it as a string, I believe. How do you get it on dart side? What plugin do you use (if any)?
You can check how we do it in react-native plugin: https://github.com/AppsFlyerSDK/appsflyer-react-native-plugin/blob/4ca80da473b794dc254aa7afe55e3f16e6d8f87b/ios/RNAppsFlyer.m#L393-L407
It comes from RN as a `NSString`

**Comment by b5710546291** [comment]
We used fcm token we get from firebase_messaging (https://pub.dev/packages/firebase_messaging). 
We currently call updateServerUninstallToken with that token which is a string and is already working for android.


I want to know that can appsflyer track from fcm token on ios side like android because  https://support.appsflyer.com/hc/en-us/articles/210289286-Uninstall-measurement#ios-uninstall  seem to me that I need apns token (We will need to separate android and ios call if fcmtoken doesn't work on ios).

**Comment by deepak786** [comment]
@b5710546291 
So we need to send the APNS token for iOS and FCM token for the Android, right?

**Comment by deepak786** [comment]
@b5710546291 @af-fess 
So we need to send the APNS token for iOS and FCM token for Android, right?

**Comment by kochityeaung** [comment]
@af-fess pls confirm that we need to send token by each platform type - android -> FCM & ios -> APN?
