### ISSUE TITLE
Calling this from your main thread can lead to deadlock

### ISSUE THREAD

**Issue by wangxingxing123654** [AppsFlyerSDK/appsflyer-flutter-plugin#56]
i called initappsflyersdk in main.dart initState(), it gives me warning like this, how to solve it ??

**Comment by af-fess** [comment]
Can you post a full log?

**Comment by wangxingxing123654** [comment]
> Can you post a full log?

not show again.

**Comment by GM-appsflyer** [comment]
Please reach out to us or support@appsflyer.com if you still encounter this issue!
