### ISSUE TITLE
ios error: cannot find 'AppsFlyerTracker' in scope #220

### ISSUE THREAD

**Issue by wangxingxing123654** [AppsFlyerSDK/appsflyer-flutter-plugin#62]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by af-fess** [comment]
Which AppsFlyer SDK version do you use?

**Comment by GM-appsflyer** [comment]
Please reach out to us or support@appsflyer.com if you still encounter this issue!
