### ISSUE TITLE
onAppOpenAttribution not defined in latest version

### ISSUE THREAD

**Issue by Cardo** [AppsFlyerSDK/appsflyer-flutter-plugin#64]
Version 6.0.5+1 on pub.dev throws 
`The method 'onAppOpenAttribution' isn't defined for the type 'AppsflyerSdk'.`

In fact, when looking at the code on the pubspec the function is not on appsflyer_sdk.dart. However, it still appears on the documentation.

Is it deprecated or replaced?

**Comment by ShaharAF** [comment]
Hi @Cardo,
`onAppOpenAttribution` and `onInstallConversionData` were added in version `6.0.5+2`

**Comment by Cardo** [comment]
Thank your very much. I wasn't able to find the updated version at pub.dev.
