### ISSUE TITLE
Using Facebook Ads & AppsFlyer SDKs for deferred deep linking

### ISSUE THREAD

**Issue by hyejobs** [AppsFlyerSDK/appsflyer-flutter-plugin#67]
Hello.

As in the link below, I would like to use the Facebook Ads for deferred deep linking, but there seems to be no facebook related function.
I tried putting the code for each OS, but it does not work properly.
How do I use the above feature in flutter?

https://support.appsflyer.com/hc/en-us/articles/207033826-Facebook-Ads-setup-guide#advanced-using-facebook-ads-appsflyer-sdks-for-deferred-deep-linking

**Comment by the-thirteenth-fox** [comment]
How to get campaign name of FB ADS by Apps Flyer listener, or this is not supported now?

**Comment by GM-appsflyer** [comment]
We'll work on adding this API

**Comment by hyejobs** [comment]
@GM-appsflyer Thanks for the reply! Could you please let me know when it will be released?

**Comment by GM-appsflyer** [comment]
@hyejobs Hopefully this week

**Comment by GM-appsflyer** [comment]
Hey @hey

We've added the Facebook API in v6.2.3+1.
Closing this ticket, but please open it again if you've encountered any related issue with this version.
Thank you!
