### ISSUE TITLE
init sdk error

### ISSUE THREAD

**Issue by LiamLong11** [AppsFlyerSDK/appsflyer-flutter-plugin#68]
init sdk on ios，I get this: 
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: 'package:appsflyer_sdk/src/appsflyer_sdk.dart': Failed assertion: line 132 pos 14: 'exp.hasMatch(appID)': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
#2      AppsflyerSdk._validateMapOptions (package:appsflyer_sdk/src/appsflyer_sdk.dart:132:14)
#3      AppsflyerSdk.initSdk.<anonymous closure> (package:appsflyer_sdk/src/appsflyer_sdk.dart:205:28)
#4      _rootRunUnary (dart:async/zone.dart:1198:47)
#5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#9      Future._complete (dart:async/future_impl.dart:519:7)

**Comment by LiamLong11** [comment]
RegExp exp = RegExp(r'^\d{8,11}$');
 assert(exp.hasMatch(appID));
appID that i get was not match this

**Comment by maxsalo17** [comment]
@LiamLong11 Just remove id prefix from your appID.

**Comment by GM-appsflyer** [comment]
Please reach out to us or support@appsflyer.com if you still encounter this issue!

**Comment by davey06** [comment]
> @LiamLong11 Just remove "id" prefix from your appID.

Hello , can you elaborate your solution? did you mean remove the `teamID`? because Apple's AppID consist of `teamID`.`bundleID`
