### ISSUE TITLE
Failed assertion: line 45 pos 12: 'devKey != null': is not true.

### ISSUE THREAD

**Issue by fedorstepanovv** [AppsFlyerSDK/appsflyer-flutter-plugin#69]
I'am trying to init my appsflyersdk, but i'm getting an issue. 
 final AppsFlyerOptions options = AppsFlyerOptions(
        afDevKey: DotEnv().env['DEVKEY'],
        appId: DotEnv().env[APPID],
        showDebug: true);
    _appsflyerSdk = AppsflyerSdk(options);
    _appsflyerSdk.initSdk();

I pasted this code to my initState. 
[ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:appsflyer_sdk/src/appsflyer_sdk.dart': Failed assertion: line 45 pos 12: 'devKey != null': is not true.

E/flutter (13160): #12     _CustomZone.run  (dart:async/zone.dart:1093:19)
E/flutter (13160): #13     _CustomZone.runGuarded  (dart:async/zone.dart:997:7)
E/flutter (13160): #14     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:1037:23)
E/flutter (13160): #15     _rootRun  (dart:async/zone.dart:1190:13)
E/flutter (13160): #16     _CustomZone.run  (dart:async/zone.dart:1093:19)
E/flutter (13160): #17     _CustomZone.bindCallback.<anonymous closure>  (dart:async/zone.dart:1021:23)
E/flutter (13160): #18     Timer._createTimer.<anonymous closure>  (dart:async-patch/timer_patch.dart:18:15)
E/flutter (13160): #19     _Timer._runTimers  (dart:isolate-patch/timer_impl.dart:397:19)
E/flutter (13160): #20     _Timer._handleMessage  (dart:isolate-patch/timer_impl.dart:428:5)
E/flutter (13160): #21     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:168:12)

What can i do? It seems like it doesn't see my key.

**Comment by fedorstepanovv** [comment]
The problem was with my .env file.

**Comment by rashmisridar** [comment]
Even I'm phasing the same issue
