### ISSUE TITLE
The callback method in the setAppInviteOneLinkID function is not called on iOS

### ISSUE THREAD

**Issue by maxsalo17** [AppsFlyerSDK/appsflyer-flutter-plugin#79]
This is the code I am using
```
appsflyer.setAppInviteOneLinkID('$id', (_) {
      print('setAppInviteOneLinkID success');
});
```
Also, when calling this method, an error is displayed in the console:
**type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'String'**

![image](https://user-images.githubusercontent.com/38714772/109041976-b072d680-76e0-11eb-9d44-c04fdc5859e8.png)

**Comment by GM-appsflyer** [comment]
Hey @maxsalo17 
We'll investigate this case and update here.

Thank you!

**Comment by GM-appsflyer** [comment]
Hey @maxsalo17!
The current version as a fix for the user invite feature.
The readme was updated with instruction was updated as well (under API-> user invite).
