### ISSUE TITLE
How can I get Invite Link

### ISSUE THREAD

**Issue by maxsalo17** [AppsFlyerSDK/appsflyer-flutter-plugin#80]
Help, I can't find in the documentation how to get invite link string in Flutter

**Comment by GM-appsflyer** [comment]
Hey @maxsalo17,
We're working on a docs and fix and we'll push an update soon!

**Comment by GM-appsflyer** [comment]
Hey @maxsalo17!
The current version as a fix for the user invite feature.
The readme was updated with instruction was updated as well (under API-> user invite).
