### ISSUE TITLE
How to get campaign name of FB ADS by AppsFlyer, or this is not supported now?

### ISSUE THREAD

**Issue by the-thirteenth-fox** [AppsFlyerSDK/appsflyer-flutter-plugin#83]

**Comment by GM-appsflyer** [comment]
We'll work on adding this API: https://support.appsflyer.com/hc/en-us/articles/207033826-Facebook-Ads-setup-guide#advanced-using-facebook-ads-appsflyer-sdks-for-deferred-deep-linking

**Comment by GM-appsflyer** [comment]
Hey @the-thirteenth-fox ,
We've added the above API in v6.2.3+1.
Closing this ticket, but please open it again if you've encountered any related issue with this version.
