### ISSUE TITLE
Failed assertion: line 45 pos 12: 'devKey != null': is not true. #69

### ISSUE THREAD

**Issue by rashmisridar** [AppsFlyerSDK/appsflyer-flutter-plugin#87]
After initializing the  appsflyersdk, but i'm getting an issue.
final AppsFlyerOptions options = AppsFlyerOptions(
afDevKey: DotEnv().env['DEVKEY'],
showDebug: true);
_appsflyerSdk = AppsflyerSdk(options);
_appsflyerSdk.initSdk();

Error:
'package:appsflyer_sdk/src/appsflyer_sdk.dart': Failed assertion: line 46 pos 12: 'devKey != null': is not true.

**Comment by GM-appsflyer** [comment]
Hey @rashmisridar,

Thank you for reaching out!
Could you specify which version of the plugin are you using?
Did you make sure to add your dev key (taken from the appsflyer dashboard -> App settings) in the env file?

**Comment by rashmisridar** [comment]
Plugin -  appsflyer_sdk: ^6.2.1+4
 Yes I have taken from the App settings. 
   
  Any Android /  IOS related configuration need to do

**Comment by GM-appsflyer** [comment]
Hey @rashmisridar ,

Could you provide us with full logs when reproducing the issue?
If it's not possible to share it here, please open a support ticket at support@appsflyer.com and share the logs there.
