### ISSUE TITLE
To disable ASIdentifierManager in OS

### ISSUE THREAD

**Issue by levent-kantaroglu** [AppsFlyerSDK/appsflyer-flutter-plugin#90]
Appstore doesn't accept appsflyer even I disabled IDFA.
It seems there is a problem with Adsupport, how can I solve this? 
Thanks

> Regarding Guideline 1.3, we continue to notice that your app references the ASIdentifierManager API, which provides access to a user's IDFA, in the following location(s) in your binary:
> 
> • /System/Library/Frameworks/AdSupport.framework/AdSupport
> 
> It would be appropriate to remove all instances of “ASIdentifierManager” from your app, even if they are not utilized in your app's functionality.

**Comment by GM-appsflyer** [comment]
Hey @levent-kantaroglu ,

Thank you for reaching out!
We're investigating this issue, and we'll work on a fix if needed ASAP.

**Comment by GM-appsflyer** [comment]
Hey @levent-kantaroglu ,

Which version of the Flutter plugin are you using?
I believe this was fixed in the latest iOS SDK version, and an update for the plugin might fix it.

**Comment by levent-kantaroglu** [comment]
Yesterday I send a build with 6.2.1+8 _(Update to iOS SDK V6.2.3)_ to AppStore.
Bu it is rejected again.

**Comment by GM-appsflyer** [comment]
Hey @levent-kantaroglu ,

Are you still experiencing this issue?

**Comment by levent-kantaroglu** [comment]
Unfortunately, yes. I got another rejection a few minutes ago.

```
    ...
    appsflyerSdk.disableSKAdNetwork(true);
    AppsFlyerOptions appsFlyerOptions = AppsFlyerOptions(
      afDevKey: Constant.afDevKey,
      appId: Constant.afAppId,
      showDebug: kDebugMode,
      disableAdvertisingIdentifier: true,
      disableCollectASA: true,
    );
    ...
```

**Comment by af-fess** [comment]
is it for "app for kids"?

**Comment by levent-kantaroglu** [comment]
Yes, ours is in app for kids category

**Comment by GM-appsflyer** [comment]
Hey @levent-kantaroglu ,
I've added strict mode (app for kids) capabilities for flutter since V6.2.4-nullsafety.5:
https://github.com/AppsFlyerSDK/appsflyer-flutter-plugin#strictMode

Please let us know if it helps in the app submission process.

**Comment by levent-kantaroglu** [comment]
I couln't find `appsflyer_sdk.podspec` in my project folder.
Could you give details?

**Comment by furyou81** [comment]
I found  appsflyer_sdk.podspec under ios/.symlinks/plugins/appsflyer_sdk

**Comment by furyou81** [comment]
regarding the build error, should we do something else,  should we use an other version of the AppsFlyerFramework?

**Comment by GM-appsflyer** [comment]
Hey @furyou81,

It seems you're editing the version: `appsflyer_sdk-6.2.4+4-nullsafety` instead of `appsflyer_sdk-6.2.4-nullsafety.5`
I've tested the `6.2.4-nullsafety.5` version and the project is building as expected.

I've updated the docs to make it more clear of the steps needed.

**Comment by furyou81** [comment]
Hi @GM-appsflyer,

Thanks for your answer, I got it now. Even when changing the dependency to 6.2.4-nullsafety.5 in pubspec.yaml, it was still 6.2.4+4-nullsafety in my pubspec.lock. I manually updated my pubspec.lock to 6.2.4-nullsafety.5 and it is building now

**Comment by GM-appsflyer** [comment]
Hey @furyou81 ,

Happy to hear!
Closing this issue, but please open again if you've encounter anything similar :)

**Comment by levent-kantaroglu** [comment]
I have sent a build  by applying these steps and it is still waiting review by Apple.
If any reject, I will inform you
