### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by SKLn-Rad** [AppsFlyerSDK/appsflyer-flutter-plugin#91]
Just so it is tracked.

We are in the progress of moving a package over to null safety and are currently blocked by your plugin to complete this work.
Give me a shout if you need help testing anything, happy to lend a hand.

**Comment by GM-appsflyer** [comment]
Hey @SKLn-Rad ,

Thanks for reaching out!

Sure we'll work on making the plugin null safety.
We'll update you here on the progress.

**Comment by GM-appsflyer** [comment]
Hey @SKLn-Rad !
We've update the plugin to Flutter 2.0 and null safety is now supported!
Closing this ticket but please open it again if you encounter any issue.

Thanks!
